# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20161211_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, verbose_name='\u7f51\u5740'),
        ),
    ]
