#!/usr/bin/python
# -*- coding:utf-8 -*-
"""
Django settings for django_nginx project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0wh*5c!woxn9m5skp9w6#)iajkf4rh%yjt1i@kqsedf670l1l)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_nginx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_nginx.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
# 把这些文件放到一起是为了用apache等部署的时候更方便
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')
#如果不想用 STATICFILES_DIRS 可以不用，都放在 app 里的 static 中也可以
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "common_static"),
     #'/path/to/others/static/',  # 用不到的时候可以不写这一行
)

# 这个是默认设置，Django 默认会在 STATICFILES_DIRS中的文件夹 和 各app下的static文件夹中找文件
# 注意有先后顺序，找到了就不再继续找了
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder"
)


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
  
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@278663275@qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = 'mail@278663275@qq.com'
EMAIL_HOST_PASSWORD = 'weiyumeizi'
DEFAULT_FROM_EMAIL = 'mail@278663275@qq.com'
#DEFAULT_FROM_EMAIL='weiyumei<278663275@qq.com>'
SERVER_EMAIL=EMAIL_hOST_USER
